spring:
  # OAuth 가져오기..!
  profiles:
    include: oauth

  # DB 설정
  h2:
    console:
      enabled: true

  # JPA 설정
  jpa:
    show-sql: true # JPA 수행 쿼리를 보여줌!
    properties:
      hibernate.format_sql: true # 보기 좋게 출력!

  # 칼라풀 로그 출력! - https://jojoldu.  tistory.com/158
  output:
    ansi:
      enabled: always

# 로깅
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
